---
- name: this playbook creates a file or dir
  hosts: all
  # become: true
  gather_facts: no
  tasks:
  - name: creating a directory
    file:
      path: /home/ubuntu/dir1
      state: directory
