---
- name: this playbook install packages
  hosts:  all
  become: true
  tasks:
  - name: Install package
    yum: 
    # name: ['git', 'make', 'gcc', 'wget', 'gzip' ]
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip
      - tar  
    when: ansible_os_family == "RedHat"
 
