---
- name: install apache2 on ubuntu and Alma Linux
  hosts: all
  become: true
  tasks:
  - name: install HTTPD
    yum:
      name: httpd
      state: present
    notify: start apache
    when: ansible_os_family == "RedHat"

  - name: start httpd
    service:
       name: httpd
       state: started
       enabled: yes
    when: ansible_os_family == "RedHat"

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

